### ISSUE TITLE
iPad Pro 11 / 12.9 inch, 3nd generation

### ISSUE THREAD

**Issue by ghost** [marchv/UIScreenExtension#4]
Please add:
case "iPad8,1", "iPad8,2", "iPad8,3", "iPad8,4":      fallthrough // iPad Pro (11 inch)
case "iPad8,5", "iPad8,6", "iPad8,7", "iPad8,8":                         // iPad Pro (12.9 inch, 3nd generation)

**Comment by ghost** [comment]
Sorry 3rd generation

**Comment by marchv** [comment]
Hi @antico :) Thanks for reminding 😅 I have added them as requested. Unfortunately, I had to do it via web browser so I haven't compiled it :S Let me know if I failed to do correctly thanks :)

**Comment by ghost** [comment]
Thx, well done
