### ISSUE TITLE
Add Swift Packages Support [SPM]

### ISSUE THREAD

**Issue by JaydenIrwin** [marchv/UIScreenExtension#7]

**Comment by Edward-Bazko** [comment]
@JaydenIrwin ,
A PR raised: https://github.com/marchv/UIScreenExtension/pull/10

**Comment by marchv** [comment]
Thanks @Edward-Bazko 👍  Closing this issue then. @JaydenIrwin please let us know if it works for you or not, thanks :)

**Comment by JaydenIrwin** [comment]
It won't work until 0.0.7 is "released".

**Comment by JaydenIrwin** [comment]
Please release 0.0.7

**Comment by Edward-Bazko** [comment]
PR: https://github.com/marchv/UIScreenExtension/pull/11
